export const TOGGLE_MOBILE_MENU = "TOGGLE_MOBILE_MENU";
export const SET_DARKMODE_ON = "SET_DARKMODE_ON";
export const SET_DARKMODE_OFF = "SET_DARKMODE_OFF";
export const OPEN_NOTIFICATION_MODAL = "OPEN_NOTIFICATION_MODAL";
export const CLOSE_NOTIFICATION_MODAL = "CLOSE_NOTIFICATION_MODAL";
